### ISSUE TITLE
AVGO Shares received is missing in Summary sheet A32/B32

### ISSUE THREAD

**Issue by sreenivasmrpivot** [hickeng/financial#89] opened 2024-03-11 02:58 UTC
AVGO Shares received is missing in Summary sheet A32/B32 is missing in the v0.1.4 x

It is shown in the "eTrade transaction log" section of usage.md though.

What is the significance of it on overall calculations? Should we add it on our own or do we need a new release of the workbook?

<img width="577" alt="AVGO Shares received is missing in Summary" src="https://github.com/hickeng/financial/assets/26660575/ed0f0e8d-d941-4af1-bf12-94a76177a782">

**Comment by jonatan-ivanov** [comment] 2024-03-11 06:45
Duplicate of https://github.com/hickeng/financial/issues/88

**Comment by hickeng** [comment] 2024-03-11 08:06
#88 is closed as well in recent v0.1.5 branch merge.

**Closed by hickeng** 2024-03-11 08:06 UTC
Labels: duplicate
